# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Api\Search\VehicleConditionSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleTypeSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleFuelTypeSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleTransmissionSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleDoorCountSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleFirstRegistrationYearSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleSeatCountSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleEquipmentSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\VehicleExteriorColorSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\BrandSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\ModelSearchCriteriaHandler:
        tags: ['app.search_condition.handler']

    App\Api\Search\SearchCriteriaHandler:
        arguments:
            - !tagged_iterator app.search_condition.handler

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
